Added branch name check

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,17 @@
 language: generic
 services:
 - docker
+script:
+- |
+    if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
+        valid_branch_regex="^(feature|bugfix|improvement|library|prerelease|release|hotfix)\/[a-z0-9._-]+$"
+        if [[ ! $TRAVIS_PULL_REQUEST_BRANCH =~ $valid_branch_regex ]]; then
+             echo "ERROR: There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your PR will be rejected. You should rename your branch to a valid name and try again."
+             exit 1
+        else 
+            echo "OK: Branch name accomplishes branch naming conventions"
+        fi
+    fi
 before_install:
 - |
   declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
